version: '3.1'
services:
  redis:
    image: redis:poc
    container_name: redis-container
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - conn_network
    ports:
      - 6379:6379

networks:
  conn_network:
    name: 'redis-network'
